<html>

<body>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="container-logo">
                    <a href="<?= $baseUrl ?>">Bookmarks</a>
                </div>
                <h1 class="card-title">Password reset.</h1>
                <p>Click the button below to reset your password. The link is valid for <?= $timeValid ?> after sending the password change request.</p>
                <a class="password-reset-button" href="<?= $resetLink ?>" target="_blank">Reset my password</a>
                <p class="text-secondary text-center">If you did not ask to change your password, please ignore this message.</p>
            </div>
        </div>
    </div>
</body>

</html>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Lobster&display=swap');

    * {
        font-family: 'Roboto', sans-serif;
        box-sizing: border-box;
        margin: 0 0;
        padding: 0 0;
    }

    body {
        background-color: #212529;
        color: white;
    }

    .container {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .container-logo {
        margin: 0px 3rem;
        text-align: center;
    }

    .container-logo a {
        font-family: "Lobster", sans-serif;
        font-weight: 400;
        font-size: 72px;
        font-style: normal;
        color: inherit;
        text-decoration: none;
        user-select: none;
    }

    .card {
        width: 100%;
        max-width: 600px;
        background-color: #2b3035;
        border: 1px solid #ffffff26;
        border-radius: 0.375rem;
    }

    .card-body {
        padding: 1rem;
        display: flex;
        flex-direction: column;
        gap: 32px;
    }

    .card-title {
        margin-top: 0;
        font-weight: 500;
        line-height: 1.2;
        text-align: center;
    }

    .password-reset-button {
        background-color: #0d6efd;
        border-radius: 0.5rem;
        width: 100%;
        text-align: center;
        color: inherit;
        text-decoration: none;
        font-size: 1.25rem;
        padding: 1rem 0.5rem;
    }

    .text-secondary {
        color: #808080;
    }

    .text-center {
        text-align: center;
    }

    @media screen and (max-width: 600px) {
        .container {
            padding: 24px;
        }

        .container-logo {
            margin: 0;
        }

        .container-logo a {
            font-size: 48px;
        }

        .card {
            width: 100%;
        }
    }
</style>