<nav class="navbar navbar-expand-lg sticky-top bg-body-secondary">
    <div class="container-xl">
        <a class="navbar-brand" href="/">
            <img src="/images/logo.svg" height="24">
        </a>
        <?php if ($_SESSION['user_id'] ?? false): ?>
            <div class="dropdown">
                <button class="btn dropdown-toggle border-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="/images/user.svg" width="38" height="38" class="rounded-circle">
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownUser">
                    <li>
                        <text class="dropdown-header">
                            <?= $_SESSION['username'] ?>
                        </text>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item" href="/dashboard">My dashboard</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="/settings">Settings</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="/signout">Sign out</a>
                    </li>
                </ul>
            </div>
        <?php else: ?>
            <a class="btn btn-primary" href="/signup">
                Join now!
            </a>
        <?php endif; ?>
    </div>
</nav>