<?php include_once PAGE_HEADER; ?>
<section class="jumbotron text-center w-100 vh-100 d-flex align-items-center">
    <div class="container">
        <img src="/images/logo.svg" height=80 class="mw-100">
        <h5 class="my-4">Save your bookmarks in one place and always have access to them.</h5>
        <p>
            <?php if (isset($_SESSION['user_id'])): ?>
                <a href="/dashboard" class="btn btn-lg btn-primary">Go to dashboard</a>
            <?php else: ?>
                <a href="/signin" class="btn btn-lg btn-primary">Sign in now!</a>
            <?php endif; ?>
        </p>
    </div>
</section>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-5 bg-body-tertiary">
    <div class="container">
        <div class="d-flex flex-row">
            <p class="text-body-secondary">Free SVG Background by <a target="_blank" href="https://bgjar.com">BGJar</a> &middot; Icons by <a target="_blank" href="https://tabler.io/icons">Tabler</a></p>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <p class="text-body-secondary">&copy 2024 Bookmarks.</p>
            <p class="mb-0 text-body-secondary">Developed by <a target="_blank" href="https://github.com/patrick642">Patrick642</a>.</p>
        </div>
    </div>
</footer>
<?php include_once PAGE_FOOTER; ?>