<?php include_once PAGE_HEADER; ?>
<?php include_once PAGE_NAVBAR; ?>
<div class="container-xl">
    <button class="add-button position-fixed bg-success rounded-circle border-0 shadow" data-bs-toggle="modal" data-bs-target="#addModal">
        <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M12 5l0 14" />
            <path d="M5 12l14 0" />
        </svg>
    </button>
    <main class="my-5">
        <div class="d-flex flex-row align-items-center">
            <h3 class="m-0">My dashboard</h3>
            <button class="btn border-0" title="Share" data-bs-toggle="modal" data-bs-target="#shareModal">
                <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M6 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                    <path d="M18 6m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                    <path d="M18 18m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                    <path d="M8.7 10.7l6.6 -3.4" />
                    <path d="M8.7 13.3l6.6 3.4" />
                </svg>
            </button>
            <div class="form-check form-switch" style="margin-left: auto; height: min-content;">
                <input <?= ($is_public) ? 'checked' : '' ?> class="form-check-input" type="checkbox" role="switch" id="bookmarksPrivacySwitch">
                <label class="form-check-label" for="bookmarksPrivacySwitch">Public</label>
            </div>
        </div>
        <?php if (count($data) === 0): ?>
            <div class="text-center my-5 py-5">
                <h1 class="text-secondary">You don't have any bookmarks yet</h1>
                <h5 class="text-secondary">Click on the green rounded button at the bottom of the screen to add your first bookmark.</h5>
            </div>
        <?php endif; ?>
        <?php foreach ($data as $r): ?>
            <div class="bookmark-card mx-auto my-4 bg-primary bg-gradient text-white">
                <div class="bookmark-card-body d-flex flex-row">
                    <a target="_blank" class="bookmark-link w-100" title="<?= $r['url'] ?>" href="<?= (parse_url($r['url'], PHP_URL_SCHEME) === NULL) ? '//' . $r['url'] : $r['url'] ?>">
                        <?= $r['title'] ?>
                    </a>
                    <div class="dropdown">
                        <button class="bookmark-dropdown-button border-0 bg-transparent" id="bookmarkMenu" data-bs-toggle="dropdown" aria-expanded="false">
                            <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M5 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                                <path d="M12 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                                <path d="M19 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                            </svg>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="bookmarkMenu">
                            <li>
                                <button class="dropdown-item" bookmark-copyurl="<?= $r['url'] ?>">
                                    <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                                        <path d="M7 7m0 2.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667z" />
                                        <path d="M4.012 16.737a2.005 2.005 0 0 1 -1.012 -1.737v-10c0 -1.1 .9 -2 2 -2h10c.75 0 1.158 .385 1.5 1" />
                                    </svg>
                                    Copy link
                                </button>
                            </li>
                            <li>
                                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#editBookmarkModal" data-id="<?= $r['id'] ?>">
                                    <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                                        <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                                        <path d="M16 5l3 3" />
                                    </svg>
                                    Edit
                                </button>
                            </li>
                            <li>
                                <button class="dropdown-item text-danger" data-bs-toggle="modal" data-bs-target="#deleteBookmarkModal" data-id="<?= $r['id'] ?>">
                                    <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M4 7h16" />
                                        <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                                        <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                                        <path d="M10 12l4 4m0 -4l-4 4" />
                                    </svg>
                                    Delete
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </main>
</div>

<!-- Add modal -->
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="addBookmarkModalLabel">Add a new bookmark</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="/dashboard/add" id="addBookmarkForm" class="d-flex flex-column gap-3 form-modal">
                    <div class="form-group">
                        <label for="bookmark_label" class="form-label">Label:</label>
                        <input type="text" class="form-control" id="bookmark_label" name="label" required>
                    </div>
                    <div class="form-group">
                        <label for="bookmark_url" class="form-label">Url:</label>
                        <input type="text" class="form-control" id="bookmark_url" name="url" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="addBookmarkForm" class="btn btn-success">Add</button>
            </div>
        </div>
    </div>
</div>

<!-- Edit modal -->
<div class="modal fade" id="editBookmarkModal" tabindex="-1" aria-labelledby="editBookmarkModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="editBookmarkModalLabel">Edit bookmark</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="/dashboard/edit" id="editBookmarkForm" class="d-flex flex-column gap-3 form-modal">
                    <div class="form-group">
                        <label for="bookmark_edit_title" class="form-label">Title:</label>
                        <input type="text" class="form-control" id="bookmark_edit_title" name="title" required>
                    </div>
                    <div class="form-group">
                        <label for="bookmark_edit_url" class="form-label">Url:</label>
                        <input type="text" class="form-control" id="bookmark_edit_url" name="url" required>
                    </div>
                    <input type="hidden" name="bookmark_id" value="">
                </form>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="editBookmarkForm" class="btn btn-primary">Edit</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete modal -->
<div class="modal fade" id="deleteBookmarkModal" tabindex="-1" aria-labelledby="deleteBookmarkModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="deleteBookmarkModalLabel">Delete bookmark</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you really want delete this bookmark?
                <form method="POST" action="/dashboard/delete" id="deleteBookmarkForm" class="d-flex flex-column gap-3 form-modal">
                    <input type="hidden" name="bookmark_id" value="">
                </form>
            </div>

            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="deleteBookmarkForm" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Share modal -->
<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="shareModalLabel">Share</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="input-group">
                    <input type="text" class="form-control" id="bookmarksShareLink" value="<?= BASE_URL . '/b?u=' . $_SESSION['username'] ?>" disabled readonly>
                    <button class="input-group-text" id="copyBookmarksShareLink">
                        <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                            <path d="M7 7m0 2.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667z" />
                            <path d="M4.012 16.737a2.005 2.005 0 0 1 -1.012 -1.737v-10c0 -1.1 .9 -2 2 -2h10c.75 0 1.158 .385 1.5 1" />
                        </svg>
                    </button>
                </div>

            </div>
        </div>
    </div>
</div>
<?php include_once PAGE_FOOTER; ?>