<?php include_once PAGE_HEADER; ?>
<section class="jumbotron text-center w-100 py-5 d-flex align-items-center">
    <div class="container">
        <img src="/images/logo.svg" height=80 class="mw-100">
        <h5 class="my-4">Save your bookmarks in one place and always have access to them.</h5>
        <p>
            <?php if (isset($_SESSION['user_id'])): ?>
                <a href="/dashboard" class="btn btn-primary">Go to dashboard</a>
            <?php else: ?>
                <a href="/signup" class="btn btn-primary">Sign up now!</a>
            <?php endif; ?>
        </p>
    </div>
</section>
<div class="container py-5">
    <div class="row">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card text-center">
                <div class="card-body">
                    <h4 class="card-title">Store</h4>
                    <p class="card-text p-4">By saving your bookmarks here, you can access them from anywhere in the world, from any device and from any browser.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card text-center">
                <div class="card-body">
                    <h4 class="card-title">Share</h4>
                    <p class="card-text p-4">By setting the visibility of your bookmarks to <b>public</b>, you can share your bookmarks with others.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 bg-body-tertiary">
    <div class="container">
        <div class="row text-center">
            <p class="text-body-secondary">Free SVG Background by <a target="_blank" href="https://bgjar.com">BGJar</a></p>
            <p class="mb-0 text-body-secondary">Icons by <a target="_blank" href="https://tabler.io/icons">Tabler</a></p>
        </div>
        <hr>
        <div class="row d-flex justify-content-between">
            <div class="col">
                <p class="text-body-secondary">&copy 2024 Bookmarks.</p>
                <p class="mb-0 text-body-secondary">Developed by Patrick642.</p>
            </div>
            <div class="col d-flex align-items-center justify-content-end">
                <a class="text-body-secondary" target="_blank" href="https://github.com/patrick642">
                    <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5" />
                    </svg>
                </a>
            </div>
        </div>
    </div>
</footer>
<?php include_once PAGE_FOOTER; ?>