<?php include_once PAGE_HEADER; ?>
<?php include_once PAGE_NAVBAR; ?>
<div class="container-xl">
    <main class="my-5">
        <h3>Settings</h3>
        <div class="card my-4">
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-body-tertiary">
                    <div class="d-flex flex-row justify-content-between">
                        <div class="d-flex flex-column justify-content-center gap-2">
                            <text>Your email address:</text>
                            <text>
                                <?= $user_email ?>
                            </text>
                        </div>
                        <div class="d-flex align-items-center">
                            <button class="btn text-primary" data-bs-toggle="modal" data-bs-target="#changeEmailModal">Change
                                email</button>
                        </div>
                    </div>
                </li>
                <li class="list-group-item bg-body-tertiary">
                    <div class="d-flex flex-row justify-content-between">
                        <div class="d-flex flex-column justify-content-center">
                            <text>Your password</text>
                        </div>
                        <div class="d-flex align-items-center">
                            <button class="btn text-primary" data-bs-toggle="modal" data-bs-target="#changePasswordModal">Change password</button>
                        </div>
                    </div>
                </li>
                <li class="list-group-item bg-body-tertiary">
                    <div class="d-flex flex-row justify-content-between">
                        <div class="d-flex flex-column justify-content-center">
                            <text>Deleting account</text>
                        </div>
                        <div class="d-flex flex-column">
                            <button class="btn text-danger" data-bs-toggle="modal" data-bs-target="#deleteAccountModal">Delete</button>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </main>
</div>
<!-- Change user email modal -->
<div class="modal" id="changeEmailModal" tabindex="-1" aria-labelledby="changeEmailModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="changeEmailModalLabel">Change your email address</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="/settings/change_email" id="changeEmailForm" class="d-flex flex-column gap-3 form-modal">
                    <div class="form-group">
                        <label for="email" class="form-label">Enter your new email address:</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="alert-container"></div>
                </form>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="changeEmailForm" class="btn btn-success">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- Change user password modal -->
<div class="modal" id="changePasswordModal" tabindex="-1" aria-labelledby="changePasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="changePasswordModalLabel">Change your account password</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="/settings/change_password" id="changePasswordForm" class="d-flex flex-column gap-3 form-modal">
                    <div class="form-group">
                        <label for="password" class="form-label">Enter your new password:</label>
                        <input type="password" class="form-control" id="password" name="pswd" required>
                    </div>
                    <div class="form-group">
                        <label for="password_repeat" class="form-label">Repeat password:</label>
                        <input type="password" class="form-control" id="password_repeat" name="pswd_repeat" required>
                    </div>
                    <div class="alert-container"></div>
                </form>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="changePasswordForm" class="btn btn-success">Save</button>
            </div>
        </div>
    </div>
</div>
<!-- Delete account modal -->
<div class="modal" id="deleteAccountModal" tabindex="-1" aria-labelledby="deleteAccountModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="deleteAccountModalLabel">Delete this account</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete your account? All your saved bookmarks will be deleted forever. <b>You can't undo this action.</b></p>
                <form method="POST" action="/settings/delete_account" id="deleteAccountForm" class="d-flex flex-column gap-3 form-modal">
                    <div class="form-group">
                        <label for="pswd_confirmation" class="form-label">Confirm your decision by entering your password:</label>
                        <input type="password" class="form-control" id="pswd_confirmation" name="pswd_confirmation" required>
                    </div>
                    <div class="alert-container"></div>
                </form>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="deleteAccountForm" class="btn btn-danger">Delete account</button>
            </div>
        </div>
    </div>
</div>
<?php include_once PAGE_FOOTER; ?>