<?php include_once PAGE_HEADER; ?>
<div class="container-xl">
    <main class="my-5 d-flex justify-content-center">
        <div class="card form-card bg-body-tertiary">
            <div class="card-body pt-0">
                <div class="d-flex justify-content-center align-items-center my-5">
                    <a href="/">
                        <img class="mw-100" src="/images/logo.svg">
                    </a>
                </div>
                <form method="POST" action="/signup">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                        <label class="form-label" for="username">Username (must be unique):</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                        <label class="form-label" for="email">Email address:</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="pswd" name="pswd" placeholder="Password" required>
                        <label class="form-label" for="pswd">Password:</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="pswd_repeat" name="pswd_repeat" placeholder="Password repeat" required>
                        <label class="form-label" for="pswd_repeat">Password repeat:</label>
                    </div>
                    <div class="alert-container mb-3"></div>
                    <div class="mb-3">
                        <button class="btn btn-primary w-100" name="submit">Sign Up</button>
                    </div>
                </form>
                <span class="d-flex flex-column align-items-center">
                    <text>Do you already have an account?</text>
                    <a href="/signin">SIGN IN</a>
                </span>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>