<?php include_once PAGE_HEADER; ?>
<?php include_once PAGE_NAVBAR; ?>
<div class="container-xl">
    <main class="d-flex justify-content-center align-items-center">
        <div class="my-5 card form-card bg-body-tertiary">
            <div class="card-body">
                <?php if ($session_message !== null): ?>
                    <div class="col-12">
                        <div class="alert alert-danger mb-0" role="alert"><?= $session_message ?></div>
                    </div>
                <?php else: ?>
                    <div class="col-12 mb-4">
                        <h3 class="text-center text-success">Email verified!</h3>
                        <p>Email has been confirmed. Now you can go to the dashboard and add your first bookmarks.</p>
                    </div>
                    <div class="col-12">
                        <span class="d-flex flex-column align-items-center">
                            <a class="btn btn-lg w-100 btn-primary" href="/dashboard">Go to dashboard</a>
                        </span>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>