<?php include_once PAGE_HEADER; ?>
<div class="container-xl">
    <main class="vh-100 d-flex justify-content-center align-items-center">
        <div class="card form-card bg-body-tertiary">
            <div class="card-body">
                <div class="d-flex justify-content-center align-items-center my-5">
                    <a href="/">
                        <img class="mw-100" src="/images/logo.svg">
                    </a>
                </div>
                <form method="POST" action="/signup">
                    <div class="col-12 mb-4">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                            <label class="form-label" for="username">Username (must be unique):</label>
                        </div>
                    </div>
                    <div class="col-12 mb-4">
                        <div class="form-floating">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                            <label class="form-label" for="email">Email address:</label>
                        </div>
                    </div>
                    <div class="col-12 mb-4">
                        <div class="form-floating">
                            <input type="password" class="form-control" id="pswd" name="pswd" placeholder="Password" required>
                            <label class="form-label" for="pswd">Password:</label>
                        </div>
                    </div>
                    <div class="col-12 mb-4">
                        <div class="form-floating">
                            <input type="password" class="form-control" id="pswd_repeat" name="pswd_repeat" placeholder="Password repeat" required>
                            <label class="form-label" for="pswd_repeat">Password repeat:</label>
                        </div>
                    </div>
                    <?php if ($session_message !== null): ?>
                        <div class="col-12 mb-4">
                            <div class="alert alert-danger" role="alert"><?= $session_message ?></div>
                        </div>
                    <?php endif; ?>
                    <div class="col-12 mb-4">
                        <button class="btn btn-lg btn-primary w-100" name="submit">Sign Up</button>
                    </div>
                </form>
                <div class="col-12">
                    <span class="d-flex flex-column align-items-center">
                        <text>Do you already have an account?</text>
                        <a href="/signin">SIGN IN</a>
                    </span>
                </div>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>