<?php include_once PAGE_HEADER; ?>
<?php include_once PAGE_NAVBAR; ?>
<div class="container-xl">
    <div class="z-3 position-fixed bottom-0 end-0 m-4 d-flex flex-column gap-3">
        <span data-bs-toggle="tooltip" data-bs-placement="left" data-bs-title="Add bookmark">
            <button class="dashboard-action-button bg-success rounded-circle border-0 shadow" data-bs-toggle="modal" data-bs-target="#addModal">
                <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M12 5l0 14" />
                    <path d="M5 12l14 0" />
                </svg>
            </button>
        </span>
    </div>
    <main class="my-5">
        <div class="d-flex flex-row align-items-center">
            <h3 class="m-0">My dashboard</h3>
            <button class="btn border-0" title="Share" data-bs-toggle="modal" data-bs-target="#shareModal">
                <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M6 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                    <path d="M18 6m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                    <path d="M18 18m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                    <path d="M8.7 10.7l6.6 -3.4" />
                    <path d="M8.7 13.3l6.6 3.4" />
                </svg>
            </button>
            <div class="form-check form-switch" style="margin-left: auto; height: min-content;">
                <input <?= $isPublic ? 'checked' : '' ?> class="form-check-input" type="checkbox" role="switch" id="bookmarksPrivacySwitch">
                <label class="form-check-label" for="bookmarksPrivacySwitch">Public</label>
            </div>
        </div>
        <?php if (count($bookmarks) === 0): ?>
            <div class="text-center my-5 py-5">
                <h1 class="text-secondary">You don't have any bookmarks yet</h1>
                <h5 class="text-secondary">Click on the green rounded button at the bottom of the screen to add your first bookmark.</h5>
            </div>
        <?php endif; ?>
        <div class="col bookmarks">
            <?php
            foreach ($bookmarks as $bookmark)
                include ROOT_DIR . '/src/View/inc/bookmark.phtml';
            ?>
        </div>
        <?php if ($userHasMoreBookmarks): ?>
            <div class="col d-flex justify-content-center align-items-center mb-3">
                <button class="btn btn-lg btn-primary" data-id="<?= $userId ?>" id="infiniteScrollButton">
                    <span class="spinner-border spinner-border-sm d-none"></span>
                    <span role="status">Load more bookmarks</span>
                </button>
            </div>
        <?php endif; ?>
    </main>
</div>

<!-- Add modal -->
<div class="modal" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="addBookmarkModalLabel">Add a new bookmark</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="/dashboard/add" id="addBookmarkForm" class="d-flex flex-column gap-3 form-modal">
                    <div class="form-group">
                        <label for="bookmark_label" class="form-label">Label:</label>
                        <input type="text" class="form-control" id="bookmark_label" name="label" maxlength="<?= $maxLabelLength ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="bookmark_url" class="form-label">Url:</label>
                        <input type="text" class="form-control" id="bookmark_url" name="url" maxlength="<?= $maxUrlLength ?>" required>
                    </div>
                    <div class="alert-container"></div>
                </form>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="addBookmarkForm" class="btn btn-success">Add</button>
            </div>
        </div>
    </div>
</div>

<!-- Edit modal -->
<div class="modal" id="editBookmarkModal" tabindex="-1" aria-labelledby="editBookmarkModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="editBookmarkModalLabel">Edit bookmark</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body position-relative">
                <form method="POST" action="/dashboard/edit" id="editBookmarkForm" class="d-flex flex-column form-modal">
                    <div class="form-group mb-4">
                        <label for="bookmark_edit_label" class="form-label">Label:</label>
                        <input type="text" class="form-control" id="bookmark_edit_label" name="label" maxlength="<?= $maxLabelLength ?>" required>
                    </div>
                    <div class="form-group mb-4">
                        <label for="bookmark_edit_url" class="form-label">Url:</label>
                        <input type="text" class="form-control" id="bookmark_edit_url" name="url" maxlength="<?= $maxUrlLength ?>" required>
                    </div>
                    <input type="hidden" name="bookmark_id" value="">
                    <div class="alert-container"></div>
                </form>
                <div class="edit-form-loading-overlay w-100 h-100 position-absolute top-0 start-0 d-flex justify-content-center align-items-center" style="background-color: var(--bs-modal-bg)">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="editBookmarkForm" class="btn btn-primary">Edit</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete modal -->
<div class="modal" id="deleteBookmarkModal" tabindex="-1" aria-labelledby="deleteBookmarkModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="deleteBookmarkModalLabel">Delete bookmark</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you really want delete this bookmark?
                <form method="POST" action="/dashboard/delete" id="deleteBookmarkForm" class="d-flex flex-column gap-3 form-modal">
                    <input type="hidden" name="bookmark_id" value="">
                    <div class="alert-container"></div>
                </form>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="deleteBookmarkForm" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Share modal -->
<div class="modal" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h1 class="modal-title fs-5" id="shareModalLabel">Share</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="input-group">
                    <input type="text" class="form-control" id="bookmarksShareLink" value="<?= BASE_URL . '/shared?u=' . $_SESSION['username'] ?>" disabled readonly>
                    <button class="input-group-text" id="copyBookmarksShareLink" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Copy share link">
                        <svg class="icon icon-tabler" width="24" height="24" viewBox="0 0 24 24">
                            <path d="M7 7m0 2.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667z" />
                            <path d="M4.012 16.737a2.005 2.005 0 0 1 -1.012 -1.737v-10c0 -1.1 .9 -2 2 -2h10c.75 0 1.158 .385 1.5 1" />
                        </svg>
                    </button>
                </div>
                <div class="alert-container mt-3"></div>
            </div>
        </div>
    </div>
</div>
<?php include_once PAGE_FOOTER; ?>