<?php include_once PAGE_HEADER; ?>
<?php include_once PAGE_NAVBAR; ?>
<div class="container-xl">
    <main class="d-flex justify-content-center align-items-center">
        <div class="my-5 card form-card bg-body-tertiary">
            <div class="card-body">
                <div class="col-12">
                    <?php if ($emailChanged): ?>
                        <h3 class="text-center text-success">Email changed!</h3>
                        <p>New email has been successfully confirmed.</p>
                        <a class="btn btn-lg w-100 btn-primary" href="/">Go to home page</a>
                    <?php else: ?>
                        <div class="col-12">
                            <div class="alert alert-danger mb-0" role="alert"><?= $session_message ?></div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>