<?php include_once PAGE_HEADER; ?>
<div class="container-xl">
    <main class="vh-100 d-flex justify-content-center align-items-center">
        <div class="card form-card bg-body-tertiary">
            <div class="card-body">
                <div class="col-12 text-center">
                    <h3 class="mb-4">Recovery email sent.</h3>
                    A special link has been sent so that you can set a new password for your account. Please check your mailbox and click on this link.
                </div>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>