<?php include_once PAGE_HEADER; ?>
<div class="container-xl">
    <main class="vh-100 d-flex justify-content-center align-items-center">
        <div class="card form-card bg-body-tertiary">
            <div class="card-body">
                <div class="d-flex justify-content-center align-items-center my-5">
                    <a href="/">
                        <img class="mw-100" src="/images/logo.svg">
                    </a>
                </div>
                <div class="col-12 mb-4">
                    <h3 class="text-center">Password reset</h3>
                    <p>Enter the email address of your account, a special link will be sent to you and you will be able to set a new password.</p>
                </div>
                <form method="POST" action="/password_reset">
                    <div class="col-12 mb-4">
                        <div class="form-floating">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Email address" required>
                            <label for="email">Email address:</label>
                        </div>
                    </div>
                    <?php if ($session_message !== null): ?>
                        <div class="col-12 mb-4">
                            <div class="alert alert-danger" role="alert"><?= $session_message ?></div>
                        </div>
                    <?php endif; ?>
                    <div class="col-12 mb-4">
                        <button class="btn btn-lg btn-primary w-100" name="submit">Send</button>
                    </div>
                </form>
                <div class="col-12">
                    <span class="d-flex flex-column align-items-center">
                        <a href="/signin">BACK</a>
                    </span>
                </div>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>