<?php include_once PAGE_HEADER; ?>
<div class="container-xl">
    <main class="vh-100 d-flex justify-content-center align-items-center">
        <div class="card form-card bg-body-tertiary">
            <div class="card-body">
                <div class="d-flex justify-content-center align-items-center my-5">
                    <a href="/">
                        <img class="mw-100" src="/images/logo.svg">
                    </a>
                </div>
                <?php if ($email === null): ?>
                    <div class="col-12 mb-4">
                        <div class="alert alert-danger text-center" role="alert"><?= $session_message ?? '' ?></div>
                    </div>
                    <div class="col-12">
                        <span class="d-flex flex-column align-items-center">
                            <a href="/password_reset">Send a new password reset link</a>
                        </span>
                    </div>
                <?php else: ?>
                    <div class="col-12 mb-4">
                        <p>Set new password for account <b><?= $email ?></b>.</p>
                    </div>
                    <form method="POST" action="/password_reset/reset">
                        <div class="col-12 mb-4">
                            <div class="form-floating">
                                <input type="password" class="form-control" id="pswd" name="pswd" placeholder="Password" required>
                                <label class="form-label" for="pswd">Password:</label>
                            </div>
                        </div>
                        <div class="col-12 mb-4">
                            <div class="form-floating">
                                <input type="password" class="form-control" id="pswd_repeat" name="pswd_repeat" placeholder="Password repeat" required>
                                <label class="form-label" for="pswd_repeat">Password repeat:</label>
                            </div>
                        </div>
                        <?php if ($session_message !== null): ?>
                            <div class="col-12 mb-4">
                                <div class="alert alert-danger" role="alert"><?= $session_message ?></div>
                            </div>
                        <?php endif; ?>
                        <input type="hidden" name="reset_key" value="<?= $_GET['key'] ?? ''; ?>">
                        <div class="col-12">
                            <button class="btn btn-lg btn-primary w-100" name="submit">Change</button>
                        </div>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>