<?php include_once PAGE_HEADER; ?>
<div class="container-xl">
    <main class="vh-100 d-flex justify-content-center align-items-center">
        <div class="card form-card bg-body-tertiary">
            <div class="card-body">
                <div class="col-12 mb-4 text-center">
                    <h3 class="mb-4 text-success">Password has been changed!</h3>
                    Now you can go back to the login page and sign in with your new password.
                </div>
                <div class="col-12">
                    <span class="d-flex flex-column align-items-center">
                        <a href="/signin">Go to login page</a>
                    </span>
                </div>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>