<?php include_once PAGE_HEADER; ?>
<div class="container-xl">
    <main class="vh-100 d-flex justify-content-center align-items-center">
        <div class="card form-card bg-body-tertiary">
            <div class="card-body">
                <div class="d-flex justify-content-center align-items-center my-5">
                    <a href="/">
                        <img class="mw-100" src="/images/logo.svg">
                    </a>
                </div>
                <form method="POST" action="/signin">
                    <div class="col-12 mb-4">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="login" name="login" placeholder="Email address or username" required>
                            <label for="login">Email address or username:</label>
                        </div>
                    </div>
                    <div class="col-12 mb-4">
                        <div class="form-floating">
                            <input type="password" class="form-control" id="pswd" name="pswd" minlength="4" placeholder="Password" required>
                            <label for="pswd">Password:</label>
                        </div>
                    </div>
                    <?php if ($session_message !== null): ?>
                        <div class="col-12 mb-4">
                            <div class="alert alert-danger mb-0" role="alert"><?= $session_message ?></div>
                        </div>
                    <?php endif; ?>
                    <div class="col-12 mb-4">
                        <button class="btn btn-lg btn-primary w-100" name="submit">Sign In</button>
                    </div>
                </form>
                <div class="col-12 mb-4">
                    <span class="d-flex flex-column align-items-center">
                        <a href="/password_reset">Forgot my password</a>
                    </span>
                </div>
                <div class="col-12">
                    <span class="d-flex flex-column align-items-center">
                        <text>Don't have an account?</text>
                        <a href="/signup">SIGN UP</a>
                    </span>
                </div>
            </div>
        </div>
    </main>
</div>
<?php include_once PAGE_FOOTER; ?>